[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "../build-target/x86_64-kernel.json"

[target.'cfg(target_os = "none")']
runner = "python3 ../task.py test"
