# https://taskfile.dev

version: "3"

vars:
    OUTPUT_DIR: build
    BOOTLOADER_DIR: bootloader
    KERNEL_DIR: kernel
    DUMP_DIR: dump
    THIRD_PARTY_DIR: third-party
    COZETTE_DIR: cozette
    EDK2_DIR: edk2

    BOOTLOADER_FILE: bootx64.efi
    KERNEL_FILE: kernel.elf
    IMG_FILE: myos.img
    ISO_FILE: myos.iso
    VDI_FILE: myos.vdi
    COZETTE_FILE: cozette.psf
    OVMF_CODE_FILE: OVMF_CODE.fd
    OVMF_VARS_FILE: OVMF_VARS.fd
    GDB_FILE: gdb.scr

    QEMU_DEVICES: |
        qemu-xhci
        ahci,id=ahci
        ide-cd,drive=disk,bus=ahci.0,bootindex=1
    QEMU_DRIVES: |
        id=disk,if=none,format=raw,file={{$.OUTPUT_DIR}}/{{$.IMG_FILE}}
        if=pflash,format=raw,readonly=on,file={{$.THIRD_PARTY_DIR}}/{{$.OVMF_CODE_FILE}}
        if=pflash,format=raw,file={{$.THIRD_PARTY_DIR}}/{{$.OVMF_VARS_FILE}}
    QEMU_ARGS: |
        -no-reboot
        -no-shutdown
        -m 4G
        -serial mon:stdio
        -monitor telnet::5678,server,nowait
        -gdb tcp::3333
        -d int,cpu_reset -D qemu_debug.log
    QEMU: qemu-system-x86_64 -accel kvm {{range .QEMU_ARGS | splitLines -}}{{if .}}{{.}} {{end}}{{end -}} {{range .QEMU_DRIVES | splitLines -}}{{if .}}-drive {{.}} {{end}}{{end -}} {{range .QEMU_DEVICES | splitLines -}}{{if .}}-device {{.}} {{end}}{{end -}}
tasks:
    clear:
        cmds:
            - rm -rf {{$.OUTPUT_DIR}}
            - rm -rf {{$.DUMP_DIR}}

    init:
        cmds:
            - mkdir -p {{$.OUTPUT_DIR}}

    build-cozette:
        dir: ./{{$.THIRD_PARTY_DIR}}/{{$.COZETTE_DIR}}
        cmds:
            - git submodule update --init --recursive
            - git fetch --tags
            - latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
            - git checkout $latestTag
            - if [ ! -f ../{{$.COZETTE_FILE}} ];then pipenv install --python 3 && pipenv run python3 ./build.py fonts ;fi
            - if [ ! -f ../{{$.COZETTE_FILE}} ];then bdf2psf --fb ./build/cozette.bdf /usr/share/bdf2psf/standard.equivalents /usr/share/bdf2psf/fontsets/Uni2.512 512 ../{{$.COZETTE_FILE}};fi

    build-edk2:
        dir: ./{{$.THIRD_PARTY_DIR}}/{{$.EDK2_DIR}}
        cmds:
            - git submodule update --init --recursive
            - git fetch --tags
            - latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
            - git checkout $latestTag
            - make -C ./BaseTools/Source/C
            - if [ ! -f ../{{$.OVMF_CODE_FILE}} ] || [ ! -f ../{{$.OVMF_VARS_FILE}} ];then ./OvmfPkg/build.sh -a X64 -b RELEASE -n 4;fi
            - if [ ! -f ../{{$.OVMF_CODE_FILE}} ];then sudo cp /usr/share/OVMF/x64/OVMF_CODE.fd ../{{$.OVMF_CODE_FILE}} && sudo chown zakki:zakki ../{{$.OVMF_CODE_FILE}};fi
            - if [ ! -f ../{{$.OVMF_VARS_FILE}} ];then sudo cp /usr/share/OVMF/x64/OVMF_VARS.fd ../{{$.OVMF_VARS_FILE}} && sudo chown zakki:zakki ../{{$.OVMF_VARS_FILE}};fi
            # - if [ ! -f ../{{$.OVMF_CODE_FILE}} ];then cp ./Build/OvmfX64/RELEASE_GCC5/FV/OVMF_CODE.fd ../{{$.OVMF_CODE_FILE}};fi
            # - if [ ! -f ../{{$.OVMF_VARS_FILE}} ];then cp ./Build/OvmfX64/RELEASE_GCC5/FV/OVMF_VARS.fd ../{{$.OVMF_VARS_FILE}};fi

    build:
        cmds:
            - task: clear
            - task: build-cozette
            - task: build-edk2
            - task: build-bootloader
            - task: build-kernel

    build-bootloader:
        dir: ./{{$.BOOTLOADER_DIR}}
        cmds:
            - task: init
            - cargo build
            - cp ./target/x86_64-unknown-uefi/debug/bootloader.efi ../{{$.OUTPUT_DIR}}/{{$.BOOTLOADER_FILE}}

    build-kernel:
        dir: ./{{$.KERNEL_DIR}}
        cmds:
            - task: init
            - cargo build
            - cp ./target/x86_64/debug/kernel ../{{$.OUTPUT_DIR}}/{{$.KERNEL_FILE}}

    makeimg:
        cmds:
            - task: build
            - qemu-img create -f raw ./{{$.OUTPUT_DIR}}/{{$.IMG_FILE}} 200M
            - mkfs.fat -n "MYOS" -F 32 -s 2 ./{{$.OUTPUT_DIR}}/{{$.IMG_FILE}} # format for FAT32
            - sudo mount -o loop ./{{$.OUTPUT_DIR}}/{{$.IMG_FILE}} /mnt
            - sudo mkdir -p /mnt/EFI/BOOT
            - sudo mkdir -p /mnt/EFI/myos
            - sudo cp {{$.OUTPUT_DIR}}/{{$.BOOTLOADER_FILE}} /mnt/EFI/BOOT/BOOTX64.EFI
            - sudo cp {{$.OUTPUT_DIR}}/{{$.KERNEL_FILE}} /mnt/EFI/myos/kernel.elf
            - sleep 0.5
            - sudo umount /mnt

    makeiso:
        cmds:
            - task: makeimg
            - dd if=./{{$.OUTPUT_DIR}}/{{$.IMG_FILE}} of=./{{$.OUTPUT_DIR}}/{{$.ISO_FILE}}

    makevdi:
        cmds:
            - task: makeimg
            - qemu-img convert -O vdi ./{{$.OUTPUT_DIR}}/{{$.IMG_FILE}} ./{{$.OUTPUT_DIR}}/{{$.VDI_FILE}}

    run:
        cmds:
            - task: makeimg
            - "{{$.QEMU}}"

    run-with-gdb:
        cmds:
            - task: makeimg
            - "{{$.QEMU}} -S"

    qemu-monitor:
        cmds:
            - telnet localhost 5678

    gdb:
        cmds:
            - "rust-gdb -x gdb.scr"

    dump:
        cmds:
            - task: build
            - mkdir -p {{$.DUMP_DIR}}
            - objdump -d {{$.OUTPUT_DIR}}/{{$.KERNEL_FILE}} > {{$.DUMP_DIR}}/dump_kernel.txt
            - objdump -d {{$.OUTPUT_DIR}}/{{$.BOOTLOADER_FILE}} > {{$.DUMP_DIR}}/dump_bootloader.txt
