# https://taskfile.dev

version: "3"

vars:
    OUTPUT_DIR: build
    BOOTLOADER_DIR: bootloader
    KERNEL_DIR: kernel
    DUMP_DIR: dump
    THIRD_PARTY_DIR: third-party

    BOOTLOADER_FILE: bootx64.efi
    KERNEL_FILE: kernel.elf
    IMG_FILE: myos.img
    ISO_FILE: myos.iso

    QEMU_DEVICES: |
        ahci,id=ahci
        ide-cd,drive=disk,bus=ahci.0
    QEMU_DRIVES: |
        id=disk,if=none,format=raw,file={{$.OUTPUT_DIR}}/{{$.IMG_FILE}}
    QEMU_ARGS: |
        -bios /usr/share/edk2-ovmf/x64/OVMF.fd
        -no-reboot
        -no-shutdown
        -m 4G
        -serial mon:stdio
        -monitor telnet::5678,server,nowait
    QEMU: qemu-system-x86_64 {{range .QEMU_ARGS | splitLines -}}{{if .}}{{.}} {{end}}{{end -}} {{range .QEMU_DRIVES | splitLines -}}{{if .}}-drive {{.}} {{end}}{{end -}} {{range .QEMU_DEVICES | splitLines -}}{{if .}}-device {{.}} {{end}}{{end -}}
tasks:
    clear:
        cmds:
            - rm -rf {{$.OUTPUT_DIR}}
            #- rm -rf {{$.THIRD_PARTY_DIR}}
            - rm -rf {{$.DUMP_DIR}}

    init:
        cmds:
            - mkdir -p {{$.OUTPUT_DIR}}
            - mkdir -p {{$.THIRD_PARTY_DIR}}

    build-fonts:
        dir: ./{{$.THIRD_PARTY_DIR}}
        cmds:
            - task: init
            # download Cozette font and convert to psf font
            - if [ ! -f cozette.psf ];then TAGNAME=`curl https://api.github.com/repos/slavfox/Cozette/releases/latest | jq ".tag_name" | sed 's/"//g'` && wget https://github.com/slavfox/Cozette/releases/download/${TAGNAME}/cozette.bdf;fi
            - if [ ! -f cozette.psf ];then bdf2psf --fb cozette.bdf /usr/share/bdf2psf/standard.equivalents /usr/share/bdf2psf/fontsets/Uni2.512 512 cozette.psf;fi
            - rm -f cozette.bdf

    build:
        cmds:
            - task: clear
            - task: build-fonts
            - task: build-bootloader
            - task: build-kernel

    build-bootloader:
        dir: ./{{$.BOOTLOADER_DIR}}
        cmds:
            - task: init
            - cargo build
            - cp ./target/x86_64-unknown-uefi/debug/bootloader.efi ../{{$.OUTPUT_DIR}}/{{$.BOOTLOADER_FILE}}

    build-kernel:
        dir: ./{{$.KERNEL_DIR}}
        cmds:
            - task: init
            - cargo build
            - cp ./target/x86_64/debug/kernel ../{{$.OUTPUT_DIR}}/{{$.KERNEL_FILE}}

    makeimg:
        cmds:
            - task: build
            - qemu-img create -f raw ./{{$.OUTPUT_DIR}}/{{$.IMG_FILE}} 200M
            - mkfs.fat -n "MYOS" -F 32 -s 2 ./{{$.OUTPUT_DIR}}/{{$.IMG_FILE}} # format for FAT32
            - sudo mount -o loop ./{{$.OUTPUT_DIR}}/{{$.IMG_FILE}} /mnt
            - sudo mkdir -p /mnt/EFI/BOOT
            - sudo mkdir -p /mnt/EFI/myos
            - sudo cp {{$.OUTPUT_DIR}}/{{$.BOOTLOADER_FILE}} /mnt/EFI/BOOT/BOOTX64.EFI
            - sudo cp {{$.OUTPUT_DIR}}/{{$.KERNEL_FILE}} /mnt/EFI/myos/kernel.elf
            - sleep 0.5
            - sudo umount /mnt

    makeiso:
        cmds:
            - task: makeimg
            - dd if=./{{$.OUTPUT_DIR}}/{{$.IMG_FILE}} of={{$.OUTPUT_DIR}}/{{$.ISO_FILE}}

    run:
        cmds:
            - task: makeimg
            - "{{$.QEMU}}"

    qemu-monitor:
        cmds:
            - telnet localhost 5678

    dump:
        cmds:
            - task: build
            - mkdir -p {{$.DUMP_DIR}}
            - objdump -d {{$.OUTPUT_DIR}}/{{$.KERNEL_FILE}} > {{$.DUMP_DIR}}/dump_kernel.txt
            - objdump -d {{$.OUTPUT_DIR}}/{{$.BOOTLOADER_FILE}} > {{$.DUMP_DIR}}/dump_bootloader.txt
