CC := gcc
CFLAGS := -I ../libc -Werror -g -m64 -nostdlib -fno-builtin -fno-stack-protector -mcmodel=large -mno-mmx -mno-sse -msoft-float -std=c11

LD := ld.lld
LDFLAGS := -z norelro --static --image-base=0xffff800000000000

LIB_DIR := ../libc
LIB := -L$(LIB_DIR) -lc

$(OUT_FILE): $(OBJ_FILES)
	mkdir -p ../bin
	make -C $(LIB_DIR)
	$(LD) $(OBJ_FILES) $(LIB) -o $@ $(LDFLAGS)

%.o: %.c
	$(CC) -c $< -o $@ $(CFLAGS)

clean:
	rm -f $(OUT_FILE) $(OBJ_FILES)

all: $(OUT_FILE)

.PHONY: clean all
