[package]
name = "bootloader"
version = "0.1.0"
edition = "2021"
authors = ["Zakki <zakki0925224@gmail.com>"]

[dependencies]
common = { path = "../common" }
uefi = { version = "0.24.0", features = ["alloc"] }
uefi-services = "0.21.0"
log = "0.4.18"
