[package]
name = "bootloader"
version = "0.1.0"
edition = "2021"
authors = ["Zakki <zakki0925224@gmail.com>"]

[dependencies]
common = { path = "../common" }
uefi = { version = "*", features = ["alloc"] }
uefi-services = "*"
log = "*"
xmas-elf = "*"

[profile.dev]
debug = true
